Lavin_blog_project/Lavin_blog_project/Lavin_blog_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from blog import views as blog_views
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views


urlpatterns = [
    path('', blog_views.PostListView.as_view()),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='registration/log_out.html'), name='logout'),


]


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

Lavin_blog_project/Lavin_blog_project/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('category/<category>', views.PostCategoryListView.as_view(), name='post_category_list'),
    path('info/', views.InfoTemplateView.as_view(), name='about_info'),
    path('post_detail/<pk>', views.PostDetailView.as_view(), name='post_detail'),
    # path('thanks/', views.ThanksTemplateView.as_view(), name='add_comments'),
    path('add_comments/<pk>', views.add_comments, name='add_comments'),
    path('post/add/', views.PostCreateView.as_view(), name='create_post'),
    path('post/drafts/', views.draftview, name='drafts'),
    path('post/update/<pk>', views.PostUpdateView.as_view(), name='update_post'),
    path('post/delete/<pk>', views.PostDeleteView.as_view(), name='delete_post'),
    path('post/publish/<pk>', views.post_publish, name='publish_post'),
    path('success/', views.success, name='success'),
    path('create/user/', views.add_user, name='add_user' )

]

Lavin_blog_project/Lavin_blog_project/blog/models.py
from django.contrib import auth
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.


class Post(models.Model):
    category_list = [
        ('Lifestyle','Lifestyle'),
        ('Health','Health'),
        ('Recipes','Recipes'),
        ('Travel','Travel'),
        ('Music','Music'),
        ('Products','Products'),
    ]
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    post_image = models.ImageField(upload_to='media/')
    post_title = models.CharField(max_length=256)
    text = models.TextField()
    category = models.CharField(max_length=40, choices=category_list)
    created_on = models.DateTimeField(auto_now=True)
    published_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.post_title

    def publish(self):
        self.published_on = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk': self.pk})

    def approve_comments(self):
        return self.comments.filter(approved_comments=True)


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=256)
    comment_text = models.TextField()
    create_date = models.DateTimeField(auto_now=True)
    approved_comments = models.BooleanField(default=False)

    def __str__(self):
        return self.comment_text

    def approve(self):
        self.approved_comments = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

Lavin_blog_project/Lavin_blog_project/blog/forms.py
from django import forms
from blog.models import Post, Comment
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['author', 'category', 'post_image', 'post_title', 'text']
        widgets = {
            # 'author': forms.TextInput(attrs = { 'class': 'textinputclass'}),
            # 'category': forms.Select(attrs={ 'class': 'textinputclass'}),

            # 'post_title':forms.TextInput(attrs={ 'class': 'textinputclass'}),
            # 'text': forms.Textarea(attrs={'class': 'postcontent'})
        }


class CommentForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].widget.attrs.update({'class': 'textinputclass'})
        self.fields['comment_text'].widget.attrs.update({'class': 'textinputclass'})

    class Meta:
        model = Comment

        fields = ('author', 'comment_text')
        # widget = {
        #     'author' : forms.TextInput(attrs={'class': 'textinputclass'}),
        #     'comment_text': forms.Textarea(attrs={'class': 'postcontent'})
        #
        #     # 'comment_text' : forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
        #   }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

Lavin_blog_project/Lavin_blog_project/blog/views.py
from datetime import datetime

from django import template
from django.contrib.auth.models import User, Group
# from django.core.checks import register
from django.http import HttpResponseRedirect, request, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from blog.models import Post, Comment
from blog.forms import CommentForm, PostForm, UserForm
from django.contrib.auth.decorators import login_required, user_passes_test


# Create your views here.
# from django_projects.Lavin_blog_project.Lavin_blog_project.blog.forms import CommentForm
# from django_projects.blog_project.Lavin_blog_project.Lavin_blog_project.blog.forms import UserForm


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list_page.html'


class PostCategoryListView(ListView):
    model = Post
    template_name = 'blog/post_list_page.html'

    def get_queryset(self):
        p = Post.objects.filter(category=self.kwargs['category'], published_on__isnull=False)
        return p


class PostDetailView(DetailView):
    model = Post
    form_class = CommentForm
    initial = {'author': 'Provide Author name', 'comment_text': 'Enter Comments here'}
    template_name = 'blog/post_detail_page.html'

    def get(self, request, *args, **kwargs):
        p_key = self.kwargs['pk']
        p = Post.objects.get(pk=p_key)
        print(p.comments.all())
        comment = self.form_class(initial=self.initial)
        # print(comment.author)
        return render(request, self.template_name, {'form': comment,
                                                    'post': p})


@login_required
def add_comments(request, pk):
    post = get_object_or_404(Post, pk=pk)
    print("post : ", post)
    if request.method == "POST":

        comment = CommentForm(request.POST)
        print("comment : ", comment)
        if comment.is_valid():
            print('valid data')
            # comment.save(commit=False)
            comment.author = request.POST['author']
            comment.comment_text = request.POST['comment_text']
            comment.post = post
            print(comment.post.id)
            # a= input(post)
            comment.save()
            print('done')
            return redirect('blog:post_detail', pk=post.pk)
        else:
            comment = CommentForm()
    return render(request, 'blog/post_detail_page.html', {'post': p, 'form': comment})


class InfoTemplateView(TemplateView):
    template_name = 'blog/about.html' \
                    ''

register = template.Library()


@register.filter('is_admin')
def is_admin(user):
    try:
        u = User.objects.get(username=user.username)
        admin_grp = Group.objects.get(name='Admin')
        return admin_grp in u.groups.all()
    except Group.DoesNotExist:
        return False


class PostCreateView(CreateView):
    model = Post
    # form_class = PostForm
    template_name = 'blog/create_post.html'
    fields = ['author', 'category', 'post_image', 'post_title', 'text']

    def get(self, request, *args, **kwargs):
        if is_admin(request.user):
            return super().get(request, *args, **kwargs)

        return HttpResponse("you don't have admin rights !!")


@user_passes_test(is_admin, login_url='/login/')
def draftview(request):
    draft_post = Post.objects.filter(published_on__isnull=True)
    return render(request, 'blog/draft_page.html', {'draft_list': draft_post})


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/update_post.html'
    fields = ['author', 'category', 'post_image', 'post_title', 'text']
    success_url = "/blog/success/"


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = "/blog/"


def success(request):
    context = {}
    msg = 'Post Updated Successfully !!!'
    context['success_msg'] = msg
    return render(request, 'blog/success.html', context)


def post_publish(request, pk):
    print('Got inside')
    post = get_object_or_404(Post, pk=pk)
    print('post', post)
    post.published_on = datetime.now()
    post.save()
    print('published updated')
    return HttpResponseRedirect(reverse('blog:post_list'))


def add_user(request):
    # admin_grp = Group.objects.get(name='admin')

    if request.method == 'POST':
        # if request.user.groups.filter(name=admin_grp):
        user = UserForm(request.POST)
        user.save()
        return HttpResponseRedirect('blog:login')
    # else:
    #        return HttpResponse("You don't have admin rights!!")
    # endif
    user = UserForm()
    return render(request, 'blog/add_user.html', {'form': user})

# class ThanksTemplateView(TemplateView):
#     comment_class = CommentForm
#     template_name = 'blog/post_detail_page.html'
#
#
#     def get(self, request, *args, **kwargs):
#         comment = self.comment_class()
#         return render(request, self.template_name, {'form': comment})
#
#     def post(self, request, *args, **kwargs):
#        # comment = self.comment_class(request.POST)
#        return HttpResponseRedirect('/post_detail/')

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %} About Myself {% endblock %}

{% block content %}
    <p>This is Preeti Basantani. I have completed Masters in Information Technology securing First Class with Distinction.</p>
    <p>This is my first ever blog. Hope you like it. It encourages me to develop some more interesting websites.</p>

{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/add_user.html
{% extends 'blog/base.html' %}
{% block title %}Login Page {% endblock %}
id
{% block content %}


{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous">

    </script>
     <script src="{% static 'js/script.js' %}" type="text/javascript"> </script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Mate+SC&family=Open+Sans&display=swap" rel="stylesheet">  <title>{% block title %} {% endblock %}</title>
</head>
<body>
  <div class="nav_container">


      <div class="logged" >
          {% if user.is_authenticated  %}
              <p class="log">Welcome {{ user.username }} |  {{ user.groups.all.0 }} | Last Login: {{ user.last_login }}</p>
              <p class="log"><a  href="{% url 'logout' %}">LogOUT</a></p>

                {% ifequal  user.groups.all.0.name 'Admin' %}
                    <p class="log"><a href="{% url 'blog:create_post' %}">New Post</a> <a href="{% url 'blog:drafts' %}">Draft</a></p>
                {% endifequal %}
          {% else %}
              <p id="logged"><a  href="{% url 'login' %}">Login</a></p>
          {% endif %}
      </div>

      <h1> My Life Journey </h1>
    <nav>
      <a id="a1" href="{% url 'blog:post_list' %}">All</a>
      <a id="a2" href="{% url 'blog:post_category_list' category='Lifestyle' %}">Lifestyle</a>
      <a id="a3" href="{% url 'blog:post_category_list' category='Health' %}">Health</a>
      <a id="a4" href="{% url 'blog:post_category_list' category='Recipes' %}">Recipes</a>
      <a id="a5" href="{% url 'blog:post_category_list' category='Travel' %}">Travel</a>

      <a id="a6" href="{% url 'blog:post_category_list' category='Music' %}">Music</a>
      <a id="a7" href="{% url 'blog:post_category_list' category='Products' %}">Products</a>
      <a id="a8" href="{% url 'blog:about_info' %}">Info</a>
    </nav>



  </div>
    <div class="base_container">
         {% block content %}
        {% endblock %}
    </div>



</body>

</html>

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}
  <div class="sub_container">
    <h2 class="center">Create New Post !!</h2>
    <form action="{% url 'blog:create_post' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
    {{ form.as_p }}
      <input type="submit" value="Create Post">
    </form>
  </div>
{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}
  <div class="sub_container">
    <form method="POST">
      {% csrf_token %}
      <h2>Are you sure, You want to delete this post? </h2>
      <input type="submit" value="Delete Post">
    </form>
  </div>
{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/draft_page.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}
  {% for e in draft_list %}
    <div class="sub_container">
        <div class="img_container">
            <a href="{% url 'blog:post_detail' e.pk  %}">
                <img src="{{ e.post_image.url }}" alt="Can't load img">
            </a>
        </div>

      <div class="lower">{{ e.category}}  </div>

      <p class="title"> {{ e.post_title }}</p>
        <span><i class="material-icons">edit</i> <a href="{% url 'blog:update_post' pk=e.pk %}">Edit</a> </span>
         <span><i class="material-icons">delete</i> <a href="{% url 'blog:delete_post' pk=e.pk %}">Delete</a></span>
         <span><i class="material-icons">publish</i> <a href="{% url 'blog:publish_post' pk=e.pk %}">Publish Post</a></span>

    </div>
  {% endfor %}

{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/post_detail_page.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}


    <div class="sub_container">
        <div class="img_container">
            <img src="{{ post.post_image.url }}" alt="Can't load img">
        </div>
        <p id="title">{{ post.post_title }}</p>
        <p id="text">{{ post.text|urlize|linebreaksbr }}</p>

        <div id="sub-container">
            <h3>Comments:</h3>
            <form action="{% url 'blog:add_comments' pk=post.pk %}" method="post">
                {% csrf_token %}
                   {{ form.as_p}}
                <input id="sub_button_right" type="submit" value="Submit" >
            </form>
                <div class="comments-container">
                {% for comment_entry in post.approve_comments %}
                    <i class="material-icons" style="font-size:35px"> person </i> <span>{{ comment_entry.author }}</span> <span id="left-align"><strong>Created on: </strong>{{ comment_entry.create_date }}</span>
                    <p>{{ comment_entry.comment_text }}</p>
                    <br>
                {% endfor %}
                </div>

         </div>

    </div>






{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/post_list_page.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}
  {% for e in post_list %}
    <div id="d{{ forloop.counter }}">
      <a href="{% url 'blog:post_detail' e.pk  %}">
        <img src="{{ e.post_image.url }}" alt="Can't load img">
      </a>
      <div class="lower">{{ e.category}}  </div>

      <p class="title"> {{ e.post_title }}</p>
      </div>

  {% endfor %}
{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/success.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}
    <div class="sub_container">
         <h1>{{ success_msg }}</h1>
    </div>
{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/thanks_page.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}
id
{% block content %}
    <p>Thanks for adding comments</p>
{% endblock %}

Lavin_blog_project/Lavin_blog_project/blog/templates/blog/update_post.html
{% extends 'blog/base.html' %}
{% block title %} ARYAN from CANADA {% endblock %}

{% block content %}
  <div class="sub_container">
    <h2 class="center">Update Post !!</h2>
    <form  method="post" enctype="multipart/form-data">
      {% csrf_token %}
    {{ form.as_p }}
      <input type="submit" value="Update Post">
    </form>
  </div>
{% endblock %}